server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  application:
    name: book-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
